services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_user
      POSTGRES_DB: cat_dog_classifier
      PGDATA: /home/ubuntu/postgres/data
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

# volumes:
#   postgres_data: {}

networks:
  app_network: {}